### ISSUE TITLE
Improve developers' documentation in README

### ISSUE THREAD

**Issue by dfucci** [OpenReqEU/ri-collection-explicit-feedback-google-play-review#2]
The README should contain a _Note for Developers_ section stating what should be modified to update the crawler when the HTML structure of the Google Play Store pages is updated.

_Originally posted by @ChristophStanik in https://github.com/OpenReqEU/ri-collection-explicit-feedback-google-play-review/issues/1#issuecomment-475671224_

**Comment by ChristophStanik** [comment]
@dfucci I updated the readme with further information.
